import Header from "@/components/Header";
import Head from "next/head";

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>D.N.A Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        ></link>
      </Head>
      <Header />
      {children}
    </>
  );
}

export default Layout;
